#!/usr/bin/env python3
"""Regenerate the checked-in engine cursor bytes; builds need no Python."""
import argparse
from pathlib import Path

repo = Path(__file__).resolve().parent.parent
names = ['pointer', 'direction-n', 'diag-ne', 'direction-e', 'diag-se',
         'direction-s', 'diag-sw', 'direction-w', 'diag-nw']
lines = ['/* Generated by scripts/embed-cursors.py from textures/cursors/*.png. */',
         '#ifndef IMPERA_CURSOR_ASSETS_H', '#define IMPERA_CURSOR_ASSETS_H']
for i, name in enumerate(names):
    data = (repo / 'textures/cursors' / f'cursor-{name}.png').read_bytes()
    lines.append(f'static const unsigned char cursor_png_{i}[] = {{')
    for offset in range(0, len(data), 16):
        lines.append('    ' + ','.join(f'0x{value:02x}' for value in data[offset:offset+16]) + ',')
    lines.append('};')
lines.append('static const struct { const unsigned char* data; int size; } cursor_pngs[] = {')
for i in range(len(names)):
    lines.append(f'    {{cursor_png_{i}, sizeof(cursor_png_{i})}},')
lines.extend(['};', '#endif', ''])
content = '\n'.join(lines)
target = repo / 'src/key/cursor_assets.h'
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
if args.check:
    if not target.exists() or target.read_text() != content:
        parser.error('Cursor bytes are stale; run python scripts/embed-cursors.py')
else:
    target.write_text(content)
